name:                 rdr-team-generator
version:              0.1.0.0
visibility:           public
id:                   rdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI
key:                  rdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI
abi:                  a656467bda1d33d3c920c3abb35b3551
exposed:              True
exposed-modules:      PontosCorridos Sorteador
hidden-modules:       Paths_rdr_team_generator
import-dirs:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\lib\x86_64-windows-ghc-9.10.3-b42a\rdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI

library-dirs:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\lib\x86_64-windows-ghc-9.10.3-b42a\rdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

library-dirs-static:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\lib\x86_64-windows-ghc-9.10.3-b42a\rdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

dynamic-library-dirs:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\lib\x86_64-windows-ghc-9.10.3-b42a
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\lib
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\bin

data-dir:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\share\x86_64-windows-ghc-9.10.3-b42a\rdr-team-generator-0.1.0.0

hs-libraries:         HSrdr-team-generator-0.1.0.0-LYd5vI3OZmrGr5op1McgHI
include-dirs:
    C:\Users\Lucas\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\mingw64\include

depends:              base-4.20.2.0-39f9
haddock-interfaces:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\doc\rdr-team-generator-0.1.0.0\rdr-team-generator.haddock

haddock-html:
    C:\Users\Lucas\programacao\rdr-team-generator\.stack-work\install\8297a369\doc\rdr-team-generator-0.1.0.0
